image: barichello/godot-ci:4.2.1

variables:
  EXPORT_NAME: fefsp0

stages:
  - export
  - deploy

windows:
  stage: export
  script:
    - sudo apt-get install libx11-6:i386
    - mkdir -v -p build/windows
    - godot -v --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

web:
  stage: export
  script:
    - sudo apt-get install libx11-6:i386
    - mkdir -v -p build/web
    - godot -v --export-release "Web" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
