image: barichello/godot-ci:3.1.1

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web

windows:
  stage: export
  script:
    - cd Godot
    - godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
      - release

mac:
  stage: export
  script:
    - cd Godot
    - godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
    - test -e ../build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
  only:
      - release

web:
  stage: export
  script:
    - cd Godot
    - godot -v --path Godot --export "HTML5" ../build/web/index.html
    - test -e ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
  only:
      - release
