name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Web, Windows Desktop]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build              
        uses: yeslayla/build-godot-action@v1.5.0
        with:
          name: FEFSP0
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
